org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.87
curios_version=15.0.0+26.1.2
artifacts_version=xrizTBU2
jei_version=OhedJ3Iu
jade_version=fnbQ0Mb3


mod_id=trainingdummy
mod_name=Training Dummy
mod_license=All Rights Reserved
mod_version=1.6
mod_group_id=com.trainingdummy
