org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.244
loader_version_range=[1,)
curios_version=9.5.1+1.21.1
artifacts_version=13.2.1
relics_version=0.12.8
shatterlib_version=yVCCi6TK
architectury_version=13.0.11+neoforge
malum_version=1.8.2
lodestonelib_version=1.8.2
mahoutsukai_version=qAJ0gGH9
oritech_version=lxLMO7bV
athena_version=dJgL278E
geckolib_version=Grwn5rUB
jei_version=Tbomhybz
guideme_version=21.1.19


mod_id=trainingdummy
mod_name=Training Dummy
mod_license=All Rights Reserved
mod_version=1.7-21.1
mod_group_id=com.trainingdummy
